name: Test and Coverage Check

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test on Ubuntu 20.04 - Python 3.11 (CI)
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests and generate coverage report
      run: |
        python -m pytest --cov=. --cov-report=xml
        python -m pip install coverage codecov
        coverage report -m
        codecov

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: declue/resource-exporter