name: Test and Coverage Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on Ubuntu 20.04 - Python 3.11
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests and generate coverage report
      run: |
        python -m pytest --cov=.
        python -m pip install coverage
        coverage report -m

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.txt

  coverage-check:
    name: Coverage Check
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Download coverage report from previous job
      uses: actions/download-artifact@v2
      with:
        name: coverage-report

    - name: Check coverage threshold
      run: |
        threshold=80
        coverage=$(grep "TOTAL" coverage.txt | awk '{print $NF}' | cut -d'%' -f1)
        if [ "$coverage" -lt "$threshold" ]; then
          echo "Code coverage is below the threshold ($coverage%). Please increase coverage to at least $threshold%."
          exit 1
        else
          echo "Code coverage is above the threshold ($coverage%)."
        fi

  merge-block:
    name: Merge Block
    needs: coverage-check
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Block PR if coverage is below threshold
      uses: peter-evans/create-pull-request-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        message: "This pull request cannot be merged because code coverage is below the required threshold."
        check_for_pr_labels: false
        check_for_open_pr: true
        check_for_updated_comments: true
