name: Test and Coverage Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on Ubuntu 20.04 - Python 3.11
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests and generate coverage report
      run: |
        python -m pytest --cov=. --cov-report=xml

    - name: Check coverage and update GitHub status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coverage=$(coverage report -m | tail -n 1 | awk '{print $NF}' | sed 's/%//')
        echo "Coverage is ${coverage}%"

        state="success"
        description="Coverage is above 80%"
        if (( $(echo "$coverage < 80" | bc -l) )); then
          state="failure"
          description="Coverage is below 80%"
        fi

        curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
        -d "{\"state\": \"${state}\", \"target_url\": \"${GITHUB_ACTIONS_URL}\", \"description\": \"${description}\", \"context\": \"code-coverage\"}" \
        https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${{ github.sha }}
